# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

# Python:
# pip install pyright (broken as of 2023-03-18)
# pip install "python-lsp-server[all]"

# Latex:
# cargo install texlab

# you can add "auto-format = true" or use "=" to format (config.toml keybinding)

[[language]]
name = "rust"
formatter = { command = "rustfmt", args = ["+nightly"] }

[[language]]
name = "markdown"
text-width = 100

[[language]]
name = "html"
auto-format = true

[[language]]
name = "python"
language-servers = ["pylsp"]
roots = [".git"]
#workspace-lsp-roots = ["src/updater"]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
flake8 = {enabled = true, ignore = ["E501"]}
autopep8 = {enabled = false}
mccabe = {enabled = false}
pycodestyle = {enabled = false}
pyflakes = {enabled = false}
pylint = {enabled = false}
yapf = {enabled = false}
ruff = { enabled = false}
