#!/usr/bin/env python3
import argparse
import sys
import random

from diffusers import StableDiffusionPipeline
from torch import Generator


def main(args):
    # https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/text2img
    pipe = StableDiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1")
    pipe.to("cuda")
    generator = Generator("cuda")
    tokens = args.prompt.split()
    n_tokens = len(tokens)
    for i in range(args.m_times):
        k = random.randint(1, n_tokens)
        prompt = ' '.join(random.sample(tokens, k))
        image = pipe(
            prompt,
            width=args.width,
            height=args.height,
            num_inference_steps=args.num_inference_steps,
        ).images[0]
        png_name = f"{prompt}-{i}.png".replace(" ", "-")
        image.save(png_name)


def parse_args(argv):
    parser = argparse.ArgumentParser(
        prog=argv[0],
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("prompt", help="prompt to generate image.")
    parser.add_argument(
        "-n",
        "--num_inference_steps",
        type=int,
        default=50,
        help="number of inference steps (higher->higher res).",
    )
    parser.add_argument("--width", type=int, default=1920, help="width in px.")
    parser.add_argument("--height", type=int, default=1080, help="height in px.")
    parser.add_argument(
        "-m",
        "--m_times",
        type=int,
        default=1,
        help="number of images to generate with this prompt.",
    )
    return parser.parse_args(argv[1:])


if __name__ == "__main__":
    args = parse_args(sys.argv)
    main(args)
